/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  motionprofiles.c
 *  model: Jiwy
 *  expmt: Jiwy
 *  date:  June 7, 2018
 *  time:  8:45:52 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

