/**********************************************************
 * This file is generated by the 20-sim C++ Code Generator
 *
 *  file:  IO_Tilt.cpp
 *  subm:  IO_Tilt
 *  model: JIWY-better-tuned
 *  expmt: JIWY-better-tuned
 *  date:  June 19, 2018
 *  time:  2:04:40 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* Standard include files */
#include <stdio.h>
#include <math.h>
/* Include the header for memcpy and memset
 * You may need to change this into <memory.h> for older compilers
 */
#include <string.h>

/* 20-sim include files */
#include "IO_Tilt.h"

/* Delta margin used for end time checking */
const XXDouble c_delta = 1.0e-7;

/* this PRIVATE function sets the input variables from the input vector */
void IO_Tilt::CopyInputsToVariables (XXDouble *u)
{
	/* copy the input vector to the input variables */
	m_V[16] = u[0];		/* angleCT */
	m_V[19] = u[1];		/* steerDT */

}

/* this PRIVATE function uses the output variables to fill the output vector */
void IO_Tilt::CopyVariablesToOutputs (XXDouble *y)
{
	/* copy the output variables to the output vector */
	y[0] = 	m_V[18];		/* angleDT */
	y[1] = 	m_V[17];		/* steerCT */

}

IO_Tilt::IO_Tilt(void)
{
	m_number_constants = 0;
	m_number_parameters = 9;
	m_number_initialvalues = 0;
	m_number_variables = 20;
	m_number_states = 0;
	m_number_rates = 0;
	m_number_matrices = 0;
	m_number_unnamed = 0;

	/* the variable arrays */
	m_C = new XXDouble[0 + 1];		/* constants */
	m_P = new XXDouble[9 + 1];		/* parameters */
	m_I = new XXDouble[0 + 1];		/* initial values */
	m_V = new XXDouble[20 + 1];		/* variables */
	m_s = new XXDouble[0 + 1];		/* states */
	m_R = new XXDouble[0 + 1];		/* rates (or new states) */
	m_M = new XXMatrix[0 + 1];		/* matrices */
	m_U = new XXDouble[0 + 1];		/* unnamed */
	m_workarray = new XXDouble[0 + 1];

	Reset(0.0);
	m_finish_time = 20.0;
}

void IO_Tilt::Reset(XXDouble starttime)
{
	m_start_time = starttime;
	m_step_size = 0.005;
	m_time = starttime;
	m_major = true;
	m_stop_run = false;

	/* Clear the allocated variable memory */
	memset(m_C, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_P, 0, (9 + 1) * sizeof(XXDouble));
	memset(m_I, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_V, 0, (20 + 1) * sizeof(XXDouble));
	memset(m_s, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_R, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_M, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_U, 0, (0 + 1) * sizeof(XXDouble));
	memset(m_workarray, 0, (0 + 1) * sizeof(XXDouble));


	state = initialrun;
}

bool IO_Tilt::IsFinished(void)
{
	return (state == finished);
}

IO_Tilt::~IO_Tilt(void)
{
	/* free memory */
	delete[] m_C;
	delete[] m_P;
	delete[] m_I;
	delete[] m_V;
	delete[] m_s;
	delete[] m_R;
	delete[] m_M;
	delete[] m_U;
	delete[] m_workarray;
}

/* the initialization function for submodel */
void IO_Tilt::Initialize (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* initialization phase (allocating memory) */
	m_initialize = true;
	m_stop_run = false;

	/* set the constants */


	/* set the parameters */
	m_P[0] = 318.3099;		/* Encoder\K */
	m_P[1] = 12.0;		/* Hold\bits */
	m_P[2] = -10.0;		/* Hold\minimum */
	m_P[3] = 10.0;		/* Hold\maximum */
	m_P[4] = 1.0;		/* PowAmp\K */
	m_P[5] = 12.0;		/* Sample\bits */
	m_P[6] = -3200.0;		/* Sample\minimum */
	m_P[7] = 3200.0;		/* Sample\maximum */
	m_P[8] = 0.0;		/* Sample\initial */


	/* set the initial values */


	/* set the states */


	/* set the matrices */


	/* (re-)initialize the integration method */
	myintegmethod.Initialize(this);
	
	/* copy the inputs */
	m_time = t;
	CopyInputsToVariables (u);

	/* calculate initial and static equations */
	CalculateInitial ();
	CalculateStatic ();
	CalculateInput ();
	CalculateDynamic ();
	CalculateOutput ();

	/* Set the outputs */
	CopyVariablesToOutputs (y);

	/* end of initialization phase */
	m_initialize = false;

	state = mainrun;
}

/* the function that calculates the submodel */
void IO_Tilt::Calculate (XXDouble *u, XXDouble *y /*, XXDouble t*/)
{
	switch (state)
	{
		case initialrun:	/* calculate the model for the first time */
			Initialize(u, y, 0.0);
			break;
		case mainrun:	/* calculate the model */
			if ( ( m_time <= (m_finish_time - m_step_size  + c_delta )) || ( m_finish_time == 0.0 ) )
			{
				/* another precessor submodel could determine the parameters of this submodel
				   and therefore the static parameter calculations need to be performed. */
				CalculateStatic ();
				CopyInputsToVariables (u);
				CalculateInput ();
				myintegmethod.Step();
				CalculateOutput ();
				CopyVariablesToOutputs (y);
			}
			else
			{
				state = finished;
			}

			if ( ( m_stop_run == true ) || (( m_finish_time != 0.0 ) && ( m_time + c_delta >= m_finish_time)) )
			{
				state = finished;
			}
			break;
		case finished:
			break;
		default:
			break;
	}
}

/* the termination function for submodel */
void IO_Tilt::Terminate (XXDouble *u, XXDouble *y /*, XXDouble t */)
{
	/* copy the inputs */
	CopyInputsToVariables (u);

	/* calculate the final model equations */
	CalculateFinal ();

	/* set the outputs */
	CopyVariablesToOutputs (y);
}


/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void IO_Tilt::CalculateInitial (void)
{

}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void IO_Tilt::CalculateStatic (void)
{
	/* Hold\lsb = (Hold\maximum - Hold\minimum) / (exp2 (Hold\bits) - 1); */
	m_V[7] = (m_P[3] - m_P[2]) / (XXExponent2 (m_P[1]) - 1.0);

	/* Hold\half_lsb = Hold\lsb / 2; */
	m_V[8] = m_V[7] / 2.0;

	/* Sample\lsb = (Sample\maximum - Sample\minimum) / (exp2 (Sample\bits) - 1); */
	m_V[14] = (m_P[7] - m_P[6]) / (XXExponent2 (m_P[5]) - 1.0);

	/* Sample\half_lsb = Sample\lsb / 2; */
	m_V[15] = m_V[14] / 2.0;

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void IO_Tilt::CalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void IO_Tilt::CalculateDynamic (void)
{

}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void IO_Tilt::CalculateOutput (void)
{
	/* steerCT = PowAmp\output; */
	m_V[17] = m_V[9];

	/* angleDT = Sample\output; */
	m_V[18] = m_V[10];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void IO_Tilt::CalculateFinal (void)
{

}



bool IO_Tilt::SetFinishTime(XXDouble newtime)
{
	if ((newtime <= 0.0) || ( newtime > m_time))
	{
		m_finish_time = newtime;
		return true;
	}

	return false;
}

