/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy
 *  expmt: Jiwy
 *  date:  June 7, 2018
 *  time:  2:05:49 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_MODELTILT_H
#define XX_MODELTILT_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern XXDouble xx_start_timetilt;
extern XXDouble xx_finish_timetilt;
extern XXDouble xx_step_sizetilt;
extern XXDouble xx_timetilt;
extern XXInteger xx_stepstilt;
extern XXBoolean xx_initializetilt;
extern XXBoolean xx_majortilt;
extern XXBoolean xx_stop_simulationtilt;

/* Model size constants */
#define xx_constants_size 0
#define xx_parameters_size 7
#define xx_initialvalues_size 3
#define xx_variables_size 12
#define xx_states_size 3

/* Variable arrays */
extern XXDouble xx_Ptilt[];
extern XXDouble xx_Itilt[];
extern XXDouble xx_Vtilt[];
extern XXDouble xx_stilt[];
extern XXDouble xx_Rtilt[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString xx_parameter_namestilt[];
extern XXString xx_initial_value_namestilt[];
extern XXString xx_variable_namestilt[];
extern XXString xx_state_namestilt[];
extern XXString xx_rate_namestilt[];
*/

/* Initialization methods */
/* Initialize complete model */
void XXModelInitializetilt (void);
/* Initialize specific model values */
void XXModelInitialize_parameterstilt(void);
void XXModelInitialize_initialvaluestilt(void);
void XXModelInitialize_statestilt(void);
void XXModelInitialize_variablestilt(void);
void XXModelTerminatetilt (void);

/* Computation methods */
void XXCalculateInitialtilt (void);
void XXCalculateStatictilt (void);
void XXCalculateInputtilt (void);
void XXCalculateDynamictilt (void);
void XXCalculateOutputtilt (void);
void XXCalculateFinaltilt (void);


#endif

