/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerPan
 *  model: Jiwy
 *  expmt: Jiwy
 *  date:  June 7, 2018
 *  time:  2:05:31 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_MODELPAN_H
#define XX_MODELPAN_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern XXDouble xx_start_timepan;
extern XXDouble xx_finish_timepan;
extern XXDouble xx_step_sizepan;
extern XXDouble xx_timepan;
extern XXInteger xx_stepspan;
extern XXBoolean xx_initializepan;
extern XXBoolean xx_majorpan;
extern XXBoolean xx_stop_simulationpan;

/* Model size constants */
#define xx_constants_size 0
#define xx_parameters_size 7
#define xx_initialvalues_size 3
#define xx_variables_size 10
#define xx_states_size 3

/* Variable arrays */
extern XXDouble xx_Ppan[];
extern XXDouble xx_Ipan[];
extern XXDouble xx_Vpan[];
extern XXDouble xx_span[];
extern XXDouble xx_Rpan[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString xx_parameter_names[];
extern XXString xx_initial_value_names[];
extern XXString xx_variable_names[];
extern XXString xx_state_names[];
extern XXString xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void XXModelInitializepan (void);
/* Initialize specific model values */
void XXModelInitialize_parameterspan(void);
void XXModelInitialize_initialvaluespan(void);
void XXModelInitialize_statespan(void);
void XXModelInitialize_variablespan(void);
void XXModelTerminatepan (void);

/* Computation methods */
void XXCalculateInitialpan (void);
void XXCalculateStaticpan (void);
void XXCalculateInputpan (void);
void XXCalculateDynamicpan (void);
void XXCalculateOutputpan (void);
void XXCalculateFinalpan (void);


#endif

