/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy
 *  expmt: Jiwy
 *  date:  June 7, 2018
 *  time:  2:05:49 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_SUBMODTILT_H
#define XX_SUBMODTILT_H

/* Our own include files */
#include "xxmodeltilt.h"

/* Submodel I/O variables */
extern XXInteger xx_number_of_inputstilt;
extern XXInteger xx_number_of_outputstilt;
extern XXDouble xx_step_sizetilt;

/* The names of the variables as used in the arrays above */
extern XXString xx_input_namestilt[];
extern XXString xx_output_namestilt[];


/* The submodel functions */
void XXInitializeSubmodeltilt (XXDouble *u, XXDouble *y, XXDouble t);
void XXCalculateSubmodeltilt (XXDouble *u, XXDouble *y, XXDouble t);
void XXTerminateSubmodeltilt (XXDouble *u, XXDouble *y, XXDouble t);
void XXCopyInputsToVariablestilt (XXDouble *u);
void XXCopyVariablesToOutputstilt (XXDouble *y);

#endif

