# TCL File Generated by Component Editor 13.1
# Fri May 25 16:15:03 CEST 2018
# DO NOT MODIFY


# 
# Motor_Controller "Motor_Controller" v1.0
# ESL21 2018.05.25.16:15:03
# PWM generator for VNH2SP30-E H-Bridge
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Motor_Controller
# 
set_module_property DESCRIPTION "PWM generator for VNH2SP30-E H-Bridge"
set_module_property NAME Motor_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ESL21
set_module_property AUTHOR ESL21
set_module_property DISPLAY_NAME Motor_Controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL NIOS_Interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file NIOS_Interface.vhd VHDL PATH ip/Motor_Controller/NIOS_Interface.vhd TOP_LEVEL_FILE
add_fileset_file Motor_Controller.vhd VHDL PATH ip/Motor_Controller/Motor_Controller.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH NATURAL 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE NATURAL
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter pwm_frequency NATURAL 20000
set_parameter_property pwm_frequency DEFAULT_VALUE 20000
set_parameter_property pwm_frequency DISPLAY_NAME pwm_frequency
set_parameter_property pwm_frequency TYPE NATURAL
set_parameter_property pwm_frequency UNITS None
set_parameter_property pwm_frequency ALLOWED_RANGES 0:2147483647
set_parameter_property pwm_frequency HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 8
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_readdata readdata Output data_width
add_interface_port slave slave_writedata writedata Input data_width
add_interface_port slave slave_byteenable byteenable Input data_width/8
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point IO
# 
add_interface IO conduit end
set_interface_property IO associatedClock clock
set_interface_property IO associatedReset reset
set_interface_property IO ENABLED true
set_interface_property IO EXPORT_OF ""
set_interface_property IO PORT_NAME_MAP ""
set_interface_property IO CMSIS_SVD_VARIABLES ""
set_interface_property IO SVD_ADDRESS_GROUP ""

add_interface_port IO enable export Input 1
add_interface_port IO C export Output 1
add_interface_port IO INB export Output 1
add_interface_port IO INA export Output 1

