/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerPan
 *  model: Jiwy
 *  expmt: Jiwy
 *  date:  June 7, 2018
 *  time:  2:05:31 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "xxmodelpan.h"
#include "xxintegpan.h"
#include "xxfuncs.h"
#include "xxsubmodpan.h"

/* The submodel I/O variables */
XXInteger xx_number_of_inputspan = 2;
XXInteger xx_number_of_outputspan = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString xx_input_names[] = {
	"in",
	"position"
,	NULL
};
XXString xx_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void XXCopyInputsToVariablespan (XXDouble *u)
{
	/* Copy the input vector to the input variables */
	xx_Vpan[7] = u[0];		/* in */
	xx_Vpan[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void XXCopyVariablesToOutputspan (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	xx_Vpan[6];		/* corr */
	y[1] = 	xx_Vpan[9];		/* out */

}

/* The initialization function for submodel */
void XXInitializeSubmodelpan (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	xx_initializepan = XXTRUE;
	xx_stepspan = 0;
	XXModelInitializepan ();
	XXDiscreteInitializepan ();

	/* Copy the inputs */
	xx_timepan = t;
	XXCopyInputsToVariablespan (u);

	/* Calculate the model for the first time */
	XXCalculateInitialpan ();
	XXCalculateStaticpan ();
	XXCalculateInputpan ();
	XXCalculateDynamicpan ();
	XXCalculateOutputpan ();

	/* Set the outputs */
	XXCopyVariablesToOutputspan (y);

	/* End of initialization phase */
	xx_initializepan = XXFALSE;
}

/* The function that calculates the submodel */
void XXCalculateSubmodelpan (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	xx_step_sizetilt = t - xx_timepan;
	xx_timepan = t;
	XXCopyInputsToVariablespan (u);

	/* Calculate the model */
	XXCalculateInputpan ();
	XXDiscreteSteppan ();
	XXCalculateOutputpan ();

	/* Copy the outputs */
	XXCopyVariablesToOutputspan (y);
}

/* The termination function for submodel */
void XXTerminateSubmodelpan (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	xx_timepan = t;
	XXCopyInputsToVariablespan (u);

	/* Calculate the final model equations */
	XXCalculateFinalpan ();

	/* Set the outputs */
	XXCopyVariablesToOutputspan (y);

	/* and terminate the model itself (releasing memory) */
	XXModelTerminatepan ();
	XXDiscreteTerminatepan ();
}

