/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy
 *  expmt: Jiwy
 *  date:  June 7, 2018
 *  time:  2:05:49 PM
 *  user:  Universiteit Twente
 *  from:  20-sim 4.7 Campus License
 *  build: 4.7.0.8692
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "xxmodeltilt.h"
#include "xxintegtilt.h"
#include "xxfuncs.h"
#include "xxsubmodtilt.h"

/* The submodel I/O variables */
XXInteger xx_number_of_inputstilt = 3;
XXInteger xx_number_of_outputstilt = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString xx_input_namestilt[] = {
	"corr",
	"in",
	"position"
,	NULL
};
XXString xx_output_namestilt[] = {
	"out" (
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void XXCopyInputsToVariablestilt (XXDouble *utilt)
{
	/* Copy the input vector to the input variables */
	xx_Vtilt[8] = utilt[0];		/* corr */
	xx_Vtilt[9] = utilt[1];		/* in */
	xx_Vtilt[10] = utilt[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void XXCopyVariablesToOutputstilt (XXDouble *ytilt)
{
	/* Copy the output variables to the output vector */
	ytilt[0] = 	xx_Vtilt[11];		/* out */

}

/* The initialization function for submodel */
void XXInitializeSubmodeltilt (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phasetilt (allocating memory) */
	xx_initializetilt = XXTRUE;
	xx_stepstilt = 0;
	XXModelInitializetilt ();
	XXDiscreteInitializetilt ();

	/* Copy the inputs */
	xx_timetilt = t;
	XXCopyInputsToVariablestilt (u);

	/* Calculate the model for the first time */
	XXCalculateInitialtilt ();
	XXCalculateStatictilt ();
	XXCalculateInputtilt ();
	XXCalculateDynamictilt ();
	XXCalculateOutputtilt ();

	/* Set the outputs */
	XXCopyVariablesToOutputstilt (y);

	/* End of initialization phase */
	xx_initializetilt = XXFALSE;
}

/* The function that calculates the submodel */
void XXCalculateSubmodeltilt (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	xx_timetilt = t;
	XXCopyInputsToVariablestilt (u);

	/* Calculate the model */
	XXCalculateInputtilt ();
	XXDiscreteSteptilt ();
	XXCalculateOutputtilt ();

	/* Copy the outputs */
	XXCopyVariablesToOutputstilt (y);
}

/* The termination function for submodel */
void XXTerminateSubmodeltilt (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	xx_timetilt = t;
	XXCopyInputsToVariablestilt (u);

	/* Calculate the final model equations */
	XXCalculateFinaltilt ();

	/* Set the outputs */
	XXCopyVariablesToOutputstilt (y);

	/* and terminate the model itselftilt (releasing memory) */
	XXModelTerminatetilt ();
	XXDiscreteTerminatetilt ();
}

